pipeline {
    agent any
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'gradle'
                    // Run the container on the node specified at the
                    // top-level of the Pipeline, in the same workspace,
                    // rather than on a new node entirely:
                    // reuseNode true
                }
            }
            steps {
                sh 'gradle build'
            }
        }
        stage('create Docker image') {
            steps {
                sh 'docker build -t donatasdicmanas/private-repo:hello-world .'
            }
        }
        stage('push image to dockerhub private repo') {
            steps {
                sh 'docker build -t donatasdicmanas/private-repo:hello-world .'
            }
        }

    }
}