pipeline {
    agent any
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'gradle'
                    reuseNode true
                }
            }
            steps {
                sh 'gradle build'
            }
        }
        stage('create Docker image') {
            steps {
                sh 'docker build -t donatasdicmanas/private-repo:hello-world-1.0 .'
            }
        }
        stage('push image to dockerhub private repo') {
            steps {
                sh 'docker push donatasdicmanas/private-repo:hello-world-1.0'
            }
        }

    }
}